// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:93bdb768-e14c-46e2-b048-601a5639ef5e",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_clXt3clkz",
    "aws_user_pools_web_client_id": "3fa32imgbqss0f0f0b0p66pg28",
    "oauth": {},
    "aws_user_files_s3_bucket": "vue-amplify-s3d5d0f2d172e5460da5264706bcd47a6c-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://zr3r3jthmzcfpfeiq5ijzjqsuq.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

module.exports.getConfig = () => {
   return awsmobile;
};